### ISSUE TITLE
Dose the  lanting dataset perform the median filtering?

### ISSUE THREAD

**Issue by wzc118** [changebo/HCCG-CycleGAN#1]
the word pictures in lanting dataset  seem rough.
![0001](https://user-images.githubusercontent.com/16779201/38606983-1f3b18ac-3daa-11e8-9ba9-c463231154d2.jpg) without preprocess(origin lanting dataset)
![0001](https://user-images.githubusercontent.com/16779201/38607023-39b6a08e-3daa-11e8-944b-7bbe6e244f20.jpg)
with preprocess (the position seems to adjust)

**Comment by changebo** [comment]
Yes, we use median filtering in preprocessing the Lanting dataset, see [here](https://github.com/changebo/HCCG-CycleGAN/blob/e5a3da20a2e2d887bcd31b5b8313e94eb468865d/preprocess/preprocess_xizhi.py#L20). You can change the kernel size to control the smoothness of the output.
