### ISSUE TITLE
   bitmap = bitmaplist[arr[x]]

### ISSUE THREAD

**Issue by wel3kxial** [changebo/HCCG-CycleGAN#2]
HCCG-CycleGAN$ python preprocess/preprocess_hw.py fonts/1252-c.gnt fonts/simhei.ttf 0.1 0.1 
  File "preprocess/preprocess_hw.py", line 97
    bitmap = bitmaplist[arr[x]]
                              ^
TabError: inconsistent use of tabs and spaces in indentation

Any suggestions please?

**Comment by changebo** [comment]
Thanks for reporting the issue. It should be fixed now. Could you try again?
