### ISSUE TITLE
Error when running testing

### ISSUE THREAD

**Issue by wel3kxial** [changebo/HCCG-CycleGAN#3]
torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...ai/tk/HCCG-CycleGAN/DenseCycleGAN/data/donkey_folder.lua:28: Did not find directory: /home/oitai/tk/HCCG-CycleGAN/DenseCycleGAN/datasets/1252-c-0.1-0.1/testA
stack traceback:
	[C]: in function 'error'
	...ai/tk/HCCG-CycleGAN/DenseCycleGAN/data/donkey_folder.lua:28: in main chunk
	[C]: in function 'dofile'
	/home/oitai/tk/HCCG-CycleGAN/DenseCycleGAN/data/data.lua:39: in function </home/oitai/tk/HCCG-CycleGAN/DenseCycleGAN/data/data.lua:29>
	[C]: in function 'xpcall'
	/home/oitai/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/home/oitai/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/oitai/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/home/oitai/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	/home/oitai/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	/home/oitai/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	/home/oitai/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
	/home/oitai/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
	/home/oitai/tk/HCCG-CycleGAN/DenseCycleGAN/data/data.lua:27: in function 'new'
	.../oitai/tk/HCCG-CycleGAN/DenseCycleGAN/data/data_util.lua:17: in function 'load_dataset'
	./data/unaligned_data_loader.lua:24: in function 'Initialize'
	test.lua:47: in main chunk
	[C]: in function 'dofile'
	...itai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

Any suggestions please?

**Comment by changebo** [comment]
This is probably because you haven't successfully run the preprocess code. Please see issue #2 and try again. Thanks.
